export default {
  Creatives: [
    "./assets/team/Shripadh Suresh.jpeg",
    "./assets/team/Shreeya Subhash Kalel.jpeg",
    "./assets/team/Radhika Bondre.jpeg",
    "./assets/team/Thameem Rasheed.jpeg",
    "./assets/team/Aditya Heshi.jpeg",
    "./assets/team/Swarnima Siddhartha.jpeg",
    "./assets/team/Anay Nitin Umalkar.jpeg",
    "./assets/team/Hari Govind.jpeg",
  ],
  Sponsorship: [
    "./assets/team/Samuel john lakra.jpeg",
    "./assets/team/Anek Anjireddy.jpeg",
    "./assets/team/Satvik.jpeg",
    "./assets/team/Laasya Choppalli.jpeg",
    "./assets/team/Y Adarsh Reddy.jpeg",
    "./assets/team/Kosaraju Jyothsna Abhay.jpeg",
    "./assets/team/Sudarshan Shivashankar.jpeg",
  ],
  Finance: [
    "./assets/team/Rakesh Varshith.jpeg",
    "./assets/team/Manikanta Varun Varma Nadimpalli.jpeg",
  ],
  Web: [
    "./assets/team/Adhith T.jpeg",
    "./assets/team/Nihar Karthikeya.jpeg",
    "./assets/team/Ajay Krishnan K.jpeg",
    "./assets/team/Krishna vamsi.jpeg",
    "./assets/team/Sai Manasa Veena.jpeg",
    "./assets/team/Abhinay Sadineni.jpeg",
  ],
  "Hospitality and Infrastructure": [
    "./assets/team/Billa Nikila.jpeg",
    "./assets/team/Perala Anudeep.jpeg",
    "./assets/team/Kumbha Akhila.jpeg",
    "./assets/team/Renikuntla Billjames.jpeg",
    "./assets/team/Manoj Sai Vardan.jpeg",
    "./assets/team/Venkata Abhiram.jpeg",
    "./assets/team/Erraram Saikumar.jpeg",
    "./assets/team/Tharun.jpeg",
    "./assets/team/Ramavath Simhadri Nayak.jpeg",
    "./assets/team/Varun Srivastava.jpeg",
    "./assets/team/Thummanapelly Shriya.jpeg",
    "./assets/team/Tumarada Padmaja.jpeg",
    "./assets/team/Katherapaka Nikhil.jpeg",
  ],
  "Workshops and Publicity": [
    "./assets/team/Syed Abrar.jpeg",
    "./assets/team/Rohith Erelli.jpeg",
    "./assets/team/Aditya Vikram Singh.jpeg",
    "./assets/team/Dasari Neha vijetha.jpeg",
    "./assets/team/Pasupuleti Ishwarya.jpeg",
    "./assets/team/Padala Sai Kowshik.jpeg",
    "./assets/team/Chunarkar Sumeeth.jpeg",
    "./assets/team/Rama Jayathi.jpeg",
    "./assets/team/Mudavath Vikeath.jpeg",
  ],
  "Public Relations": [
    "./assets/team/Swapnil Rawal.jpeg",
    "./assets/team/Surya Tarun.jpeg",
    "./assets/team/Rahul Metta.jpeg",
    "./assets/team/Ashish Sam.jpeg",
    "./assets/team/Santi Ashok.jpeg",
  ],
  Events: [
    "./assets/team/Deekshitha Yakasiri.jpeg",
    "./assets/team/Sriram Varma.jpeg",
    "./assets/team/Devashish Boini.jpeg",
    "./assets/team/Vishnu Shaji.jpeg",
    "./assets/team/Praveen Prakash.jpeg",
    "./assets/team/Jaswanth Kumar.jpeg",
    "./assets/team/Shiny Jillella.jpeg",
    "./assets/team/Karthikeya Hanu Prakash.jpeg",
    "./assets/team/Shaik Police Parvez.jpeg",
    "./assets/team/Sunkaraboina Uday K.jpeg",
    "./assets/team/Ruvva Suraj Kumar.jpeg",
    "./assets/team/Nidhi Raj.jpeg",
    "./assets/team/Nagarthi Niharika.jpeg",
    "./assets/team/Talasu Sowmith.jpeg",
    "./assets/team/Vadthya Ram Charan.jpeg",
  ],
  "Pronites and Productions": [
    "./assets/team/Chakka Surya Saketh.jpeg",
    "./assets/team/Ananya S Reddy.jpeg",
    "./assets/team/Karthik Kunchala.jpeg",
    "./assets/team/K SaiTeja.jpeg",
    "./assets/team/Jp Kanishka.jpeg",
    "./assets/team/Mayank Parasramka.jpeg",
    "./assets/team/Ved Santosh Khilari.jpeg",
    "./assets/team/Vevek Manda.jpeg",
  ],
  Multimedia: [
    "./assets/team/Sreevas T M.jpeg",
    "./assets/team/M Prince Akshay S.jpeg",
    "./assets/team/Gunnam Sri Satya Koushik.jpeg",
    "./assets/team/Tanish Reddy.jpeg",
    "./assets/team/Nenavath Arjun.jpeg",
    "./assets/team/Karri Eshmith Saideep.jpeg",
    "./assets/team/Vishnu Bhanavath.jpeg",
    "./assets/team/Banavath Venu Naik.jpeg",
  ],
};
